Vagrant.configure("2") do |config|
    config.vm.box = "debian/contrib-buster64" 
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081
  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php libapache2-mod-php
      service apache2 restart
      # Скачивание и размещение index.html
      curl https://raw.githubusercontent.com/Fenikks/devops-files-23.08/master/02-tools/files/index.html -o /var/www/html/index.html
      # Скачивание и размещение index.php
      curl https://raw.githubusercontent.com/Fenikks/devops-files-23.08/master/02-tools/files/index.php -o /var/www/html/index.php
    SHELL
  end